events { worker_connections 1024; }
http {
    upstream backend_agents {
        server agent:8000; # Nginx tự động tìm các container scale
    }
    server {
        listen 80;
        location / {
            proxy_pass http://backend_agents;
        }
    }
}